---
- name: "Update repos"
  ansible.builtin.apt:
    update_cache: true

- name: "Get packages to update"
  ansible.builtin.shell:
    cmd: apt list --upgradable
  register: debian_packages_update
  changed_when: false

- name: "Show packages list to update"
  ansible.builtin.debug:
    msg: "{{ debian_packages_update.stdout_lines }}"
  when: debian_packages_update.stdout_lines | length > 0

- name: "Update servers"
  ansible.builtin.apt:
    upgrade: full
    autoremove: true
