#SPDX-License-Identifier: MIT-0
---
# vars file for nvchecker

keyfile_path: "/home/ansible/.config/nvchecker/keyfile.toml"
config_path: "/home/ansible/.config/nvchecker/nvchecker.toml"
user: "ansible"
